### ISSUE TITLE
Search: integrate component

### ISSUE THREAD

**Issue by davekellam** [ObjectiveSubject/ccl#18]
* [x] Remove slug content and hide results div initially
* [x] Append search count and link rather than modify existing
* [x] Direct main search to WorldCat if return or search button pressed
* [x] wire up dropdown modifiers (keywords, authors, etc), should change url parameters when search is directed towards WorldCat (both inline and when return is hit)

**Comment by Jessdwilson** [comment]
From our call with client, they requested a 3-part search box with the following priorities 

1. research guide

2. librarian associated with research guide

3. offer site info outside of research like FAQs

https://docs.google.com/document/d/14larEOwOxJowzgu02X3t96PTjprdSvAZy6RuzTsx6DM/edit?ts=59b032ba

**Comment by davekellam** [comment]
The dropdowns will pass parameters to the search string. This will work for the databases, but we need to know the names and id numbers of the relevant databases. The keyword/title/etc modifier is slightly more problematic. To make those searches, you seem to have to wrap the queries in a two-letter code syntax. That said, we should be able to do this with javascript. I was thinking this might not be a good idea if people are used to being able to string together things like a keyword AND title search. The current site has tabs for “all”, articles and books, which _can_ be modified via parameter (I forgot keyword/author/title didn't behave like that).

We need:
* [x] Databases and ids
* [x] Clarification: is it a good idea to wrap the whole query in a specific search index (keyword, title, etc)

**Comment by davekellam** [comment]
Added databases to dropdown in commit dd44a231, but tagged the wrong issue. I've added in what seem to be the main search databases on WorldCat. Should be working now.

**Comment by davekellam** [comment]
Both dropdowns should be functioning now.

**Comment by davekellam** [comment]
I'm going to close this out, the component is integrated. Any further refinements to the visual presentation or query results can have their own new issue.
