### ISSUE TITLE
Accordians

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#21]
added as an option to WP site

**Comment by Jessdwilson** [comment]
from Gabriel: We noticed that sometimes the accordion shortcode adds a `<br>` tag in between accordion sections... Is this something we are doing wrong? They don't seem to be appearing on other pages with accordion shortcodes.

**Comment by kpettinga** [comment]
@Jessdwilson 

Can we see an example? 

Accordions should be written as follows:

[accordion title="My Title"]    

content...    

[/accordion]

[accordion title="My title"]    

content...    

[/accordion]

- opening and closing [accordion ]shortcode tags should always be on their own line
- When adding more than one, make sure to start on a new line for each.

**Comment by kpettinga** [comment]
Closing this issue out as they seem to be well on their way with Accordions. If new issues arise, please make a new issue.
