### ISSUE TITLE
Long scroll with side scrolling

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#22]

**Comment by kpettinga** [comment]
@Jessdwilson @davekellam can either of you provide clarity on what this is or where its found in our design?

**Comment by Jessdwilson** [comment]
**from Dave B.**: we plan to employ the long scroll with side-scrolling sections (per the “collections” part of the visual design) for a couple very important areas – the most important being the collections scroll. I don’t know if that needs to be a separate template or just individual components to make up that page, but we need to see how that will look in the long scroll format, and add scoped searches.

**Comment by kpettinga** [comment]
This isn't really an "issue". More of a desired functionality which will get fulfilled by other issues. Namely #24, #25, #34, and #37
