### ISSUE TITLE
Featured Item boxes

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#24]

**Comment by kpettinga** [comment]
@Jessdwilson @davekellam can either of you provide clarity on what this is or where its found in our designs?

**Comment by Jessdwilson** [comment]
could this be the featured item promo boxes? http://ccl.obsub.xyz/components/

**Comment by kpettinga** [comment]
@Jessdwilson what part of that page are you referring to? ☝️

**Comment by Jessdwilson** [comment]
**from Gabriel:** 
>My understanding is on the components page, it’s titled as “Default Promo”. So the featured item list that isn’t a carousel. That’s my understanding. Is this different from what yall envisioned?

![image](https://user-images.githubusercontent.com/1746410/30952160-06390070-a427-11e7-96fb-bffc673c54d2.png)

**Comment by kpettinga** [comment]
Folding this issue into #25. They are essentially the same component. If there are more than 3 items to display, we'll enable the carousel. Otherwise, it will just be a promo without a carousel.
