### ISSUE TITLE
Internal/External Blogs

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#26]

**Comment by kpettinga** [comment]
Need more details from CCL

**Comment by kpettinga** [comment]
**From Dave B.**
>We have need for a few blogs for the site, one example being that Special Collections runs a blog to announce and explicate newly acquired materials – it’s a bit too long winded for inclusion just in a promotional box on the site, and so they use the blog to discuss the impact of new acquisitions.

**Comment by Jessdwilson** [comment]
with regards to the blogs, Gabriel asked: I know there are a couple of blogs that does include the special collections blog and a staff blog. Let me create a finalized list for you during our meeting tomorrow.
 
What do you think though? It’s not clear to me when we need to use our multisite, or when we should rely on the main post type, as you indicated. Right now, I think the best course would be to use the multisite functionality for our blogs. Is this the right use-case for multisite? I would definitely like to hear your opinion first.

**Comment by kpettinga** [comment]
@Jessdwilson @gabrielo-cuc yes, multisite should be used for all external blogs. If there's an internal blog that your department maintains we can fold it into the theme were building for the main CCL install.
