### ISSUE TITLE
Personal contact image box/circle

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#27]

**Comment by kpettinga** [comment]
@Jessdwilson @davekellam can either of you provide clarity on what this is or where its found in our designs?

**Comment by Jessdwilson** [comment]
do you think that could be these image circles?

[CCL Website Creative Refinements 20170627 TE pg 19.pdf](https://github.com/ObjectiveSubject/ccl/files/1325003/CCL.Website.Creative.Refinements.20170627.TE.pg.19.pdf)

**Comment by kpettinga** [comment]
should create a custom block type for this.

**Comment by kpettinga** [comment]
This is all set. An example can be seen on the home page of libraryweb.wpengine.com

@davekellam, Dave B mentioned wanting a link to schedule an appointment with a librarian. I know we already setup a shortcode for the scheduling widget. Is it possible to activate that widget when we click the "Make an appointment..." link on these staff profile blocks?

![image](https://user-images.githubusercontent.com/1746410/32329875-9a792b52-bfde-11e7-8dda-c536e0964f20.png)

**Comment by davekellam** [comment]
`echo do_shortcode( '[scheduler]' );` should work (and you can use the various parameters)
