### ISSUE TITLE
Lists of guides and people by subject

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#29]

**Comment by kpettinga** [comment]
@davekellam I'm assuming this is a backend task having to do with ingesting Libguides? Let me know if there's some front-end work to be done.

**Comment by davekellam** [comment]
Both guides and staff are ingested from LibGuides and have subjects available as something that could be imported. I could create a shared taxonomy and make sure terms get created/applied for each imported item. I don't know if any consideration has been given to common names across the two, but can always just try and see. 

The other option is to create a taxonomy and for them to manage subject associations manually after import.

**Comment by kpettinga** [comment]
Hey @davekellam, 

Yeah I think your first idea would be best. Setup a shared taxonomy and have terms get created from each imported item.

Also, in a Slack message from Tue. 9/19, @gabrielo-cuc mentioned using the [Words API](https://www.wordsapi.com/) to generate terms.    
☝️ is that part of this issue?

**Comment by davekellam** [comment]
Guides and staff both pull in the subjects that have been applied in LibGuides. Those subjects are pulled into a custom taxonomy or applied if they already exist.
