### ISSUE TITLE
Related pages function 

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#34]
related pages displayed at bottom of screen?

**Comment by davekellam** [comment]
Main question here: Is this automated or curated?

If it's automated, we probably need to use something like Jetpack's Related Posts or something similar, as most related posts plugins are [disallowed by WPE](https://wpengine.com/support/disallowed-plugins/) (they tend to be database intensive). We could also do something like display a few posts from a shared taxonomy term, but it's likely to be less accurate.

If it's curated, we would want likely want a custom field with a post picker that allows selection from the appropriate post types.

**Comment by kpettinga** [comment]
@davekellam 

**lets go the custom field route here**. Can you setup a custom field to select multiple pages?

**Comment by davekellam** [comment]
@kpettinga the custom field to select related pages is in place, as is basic content and markup. Needs a little bit of finessing now.
