### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/ccl#36]

**Comment by Jessdwilson** [comment]
FYI, from Gabriel:

Here's a use case we were thinking of. There will be pages where we would have additional contextual information about doing academic research. For example, say we were describing a list of resources related to a topic without taking the user to another page. I imagine that the breadth of this content would be too deep for a tooltip, but the content would not be enough warrant a new page, and moving to another page might add to cognitive load. So in this case, a modal might be a balanced approach. 

Another use case could be a quick contact form for a librarian presented on pages that also have deep/specialized content. For the first example, I'm thinking a shortcode might be the better option. 

KP: I think a shortcode for your first example would be appropriate. We could make a shortcode that would let you define a toggle as well as content for a modal.
For your other use case concerning a form, that would probably be beyond the scope of a shortcode. When we get to a specific page that needs something like that, let's revisit and we can think of the best way forward
