### ISSUE TITLE
Custom Content Blocks

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/ccl#37]
We need to make some repeatable content blocks with different layout options (same kinda thing as CGU). Layouts I can think of right now are:

- Carousel
- Banner (full-width image)
- WYSIWYG (just a wysiwyg editor)
- ??? 

will post more if I think of them

**Comment by kpettinga** [comment]
@Jessdwilson these should be ready for Gabriel and the team to test out. 

Will create some examples for them to reference on their staging site.

**Comment by kpettinga** [comment]
See http://libraryweb.wpengine.com/collections/ for examples

**Comment by Jessdwilson** [comment]
Dave Bolinger requested:  One very important addition that we would like in the custom block dropdown is for a **single feature item box**, which could be either right or left justified, together with text on whichever side the feature picture is not on.

**Comment by kpettinga** [comment]
@Jessdwilson This is all set. I've added a "single feature item" content block type which they can choose the layout for: image right or image left.

I'm going to close this issue because I think we've pretty much fleshed out what they need so far. If something is broken or needs to change, please make a new issue.
