### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#38]
from Gabriel: on the rarest of occasions, a table might be necessary, does our wysiwyg have a table element? I understand that there are responsive concerns about using tables, but we can flesh out those details later

___

I didn't see a table option in the wysiwyg editor, is it possible to add?

**Comment by kpettinga** [comment]
@Jessdwilson they should install this plugin: https://wordpress.org/plugins/mce-table-buttons/

**Comment by davekellam** [comment]
Plugin is installed and now active
