### ISSUE TITLE
Search box visual presentation tweaks

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/ccl#39]
**Visual Presentation Ideas:**

- [x] Making a clear distinction between WMS search and the live search pre-results
- [x] Indicating WMS search with a “call to action” font and/or background color
- [x] Possibly segmenting search results into categories with labels
- ❓  Including a description of what the librarian can offer to the user. Ie. “Contact this librarian for research consultation, reference, instructions, etc etc”
- [x] Describe the retrieved resources as suggested resources and available resources. Supplemental information only, and is NOT the exhausted results from WMS

source: https://docs.google.com/document/d/14larEOwOxJowzgu02X3t96PTjprdSvAZy6RuzTsx6DM/edit?ts=59b032ba

**Comment by kpettinga** [comment]
@gabrielo-cuc re:
> Including a description of what the librarian can offer to the user. Ie. “Contact this librarian for research consultation, reference, instructions, etc etc”

This kind of information is not available in the set of data that gets imported. Where do you suggest we draw it from? Should it maybe just be a list of the librarian's subjects? Alternatively we could create a custom field for you to populate this information yourself but that might be a bit time consuming.

**Comment by gabriel-ortiz** [comment]
@kpettinga 
This is a good point, thanks Kirk. So a couple of ideas. If the API has the associated subjects for librarians, can we pull that data in for the description? If the API doesn't return this data, then I'm thinking we could have a boilerplate statement for each librarian that is served up from the searchbox. This would be a fine solution as long as we have the ability to edit that statement. Perhaps we can include as setting in the settings page?

**Comment by kpettinga** [comment]
Spinning off into a new issue here. See #48
