### ISSUE TITLE
Implement Search box behaviors

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/ccl#40]
- [x] Worldcat search should go out to worldcat site
- [x] Order results by post type. Order => Guides, Databases, Librarians, Pages, FAQ
- [ ] ~~~Librarian result should provide CTA to book appointment~~~
- [x] LibGuide result should link out to 3rd party site
- [x] FAQ result should link out to 3rd party site
- [x] Any internal page returned in results would just go to that page

**Comment by davekellam** [comment]
For the librarian result, should we link to an internal librarian page or have an inline ajaxy popup with librarian profile and the scheduler widget?

**Comment by davekellam** [comment]
The `[scheduler]` widget might force the result to a separate page. The shortcode creates a button that invokes a libcal inline popup. So, it might be jarring to have an inline result with a popup on top of it.

**Comment by kpettinga** [comment]
@davekellam everything except internal pages should link out to their respective resource (worldcat, libcal, database url, whatever)

**Comment by kpettinga** [comment]
I think for librarians, because of the fact that the scheduler needs to append scripts and a button, we should just link out to that person's profile page. We can explain to Dave B and Gabriel why that's the best option.

**Comment by davekellam** [comment]
I was thinking, there's not really much point in creating a librarian page with the sole purpose of allowing the scheduler scripts to appear... mostly because our current behaviour of linking to the profile page has a button with the same popup. So, I would say leave it as is for now, linking out to the 3rd party site.

**Comment by gabriel-ortiz** [comment]
Can we slightly modify the order of post types to be Guides, Librarians, Pages, FAQ, Databases?

**Comment by kpettinga** [comment]
Should be all set @gabrielo-cuc
