### ISSUE TITLE
Rooms: UI enhancements

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/ccl#46]
- [x] time slot times should display west coast time, not the local time. (input values are fine, just a matter of presentation).
- [x] Ability to make another booking after a submission 
- [x] show schedule for rooms from open to close. many rooms are open past midnight which is technically the following day. when requesting a availability for a certain day, slots for 12am-1am the following day do not get returned. Probably need to query 2 days at time, then use some logic to parse out what the actual open-close times are.
- [x] Add a visual indicator somewhere in the dialog box to indicate when a submission or request for availability is in progress.

See http://libraryweb.wpengine.com/meeting-and-presentation-spaces/ for a live example of the room reservation system

**Comment by davekellam** [comment]
I added the multiday booking check in f07c88fb. Right now, it's set to span the first day and day after, but could be modified to grab the whole week's bookings.

See `get_space_item()` and the line `$date->modify( '+1 day' );`. For the whole week, that can be change to 6 days, or commented out to continue receiving the current day.
