### ISSUE TITLE
Footer: ability to add custom content

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/ccl#47]
Need 2 custom fields (wysiwyg) for footer columns

![image](https://user-images.githubusercontent.com/1746410/32376639-a5e64520-c0a5-11e7-804e-9901e55c640f.png)

**Comment by davekellam** [comment]
Should we use the WordPress widget system for this?

**Comment by kpettinga** [comment]
@davekellam yeah that might work. we'll need to be able to create icons though. I know we have the shortcode. will that work in the widget system?

**Comment by davekellam** [comment]
I've added in an options page under Settings > Footer, that allows for two content columns. Those will pass the `the_content` filter to display, so html and shortcodes can be used.

It might be a bit clunky, but works for now without getting into creating very specific content entry fields (twitter, instagram, address, etc).
