### ISSUE TITLE
Add [button] shortcode

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/ccl#53]
`[button url="" size="" style=""]text[/button]`

**Should have the following attributes**:

Attribute | Description/Choices/Default
---|---
url | web address (required)
size | "small" / default: ""
style | "solid" / default: ""

**Markup examples**:

_default_
`<a href="$url" class="ccl-b-btn">Button text</a>`

_size="small"_
`<a href="$url" class="ccl-b-btn ccl-is-small">Button text</a>`

_style="solid"_
`<a href="$url" class="ccl-b-btn ccl-is-solid">Button text</a>`

**Comment by davekellam** [comment]
`[button]` shortcode is now implemented with url, size and style attributes.
