### ISSUE TITLE
Notification Area should populate from 3rd party library API

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/ccl#55]
Can talk to @gabrielo-cuc about where to find the resources for this

![image](https://user-images.githubusercontent.com/1746410/32783425-f5e712da-c94b-11e7-871f-bac8e0797f88.png)

**Comment by gabriel-ortiz** [comment]
@kpettinga @davekellam  Hey yall, I 'll share some resources for this on Slack. This part is pretty easy

**Comment by kpettinga** [comment]
From Gabriel:

---

### Calendar events

Here are some calendar resources to get started. For upcoming events. We are using a master calendar called "Love your library" You can easily target this calendar with the API. It's an Enpointv1.0, so no access token needed. Calendar ID is `1889`  and it needs the user ID also `333`. Here's a simple snippet that I use with Guzzle, that you can easily convert to `wp_remote_post`
```php
$response = $client->request('GET', 'https://api2.libcal.com/1.0/events/?', [
        'query' => [
                'iid'       => '333',
                'cal_id'    => '1889',
                'key'       => LIBCAL_KEY                                
            ]
    ]    
);
```
here's the key too: `7890b35a5725ef6e392809ccd43cfd05`

---

### Library Hours

The Hours comes in a variety of formats. Probably best if I point you over to that data. Head over to https://claremont.libcal.com/admin_hours_widgets.php and click on the "Widgets" tab.

**Comment by davekellam** [comment]
I've taken a first pass at implementing these things:

* _hours_ - should be populating dynamically, currently have a transient set to update every 3 hours
* _events_ - currently pulling in the first event from the API results, transient set to update every 15 minutes
* _notices_ - added a helper function that pulls a random notice out of some dummy data, how should this get populated (dynamically from somewhere, or a place in the wp backend)?

**Comment by gabriel-ortiz** [comment]
@davekellam Lemme run this by Dave B and hear his thoughts, especially about the notices. I think we are heading the right way though. I'd like to explore more about what use-cases we might employ. Also - potential UI enhancement for the hours - would it be possible to do a hide/show for all the library hours - and also add a hyperlink to the "Hours" page somewhere near the current hours?
