### ISSUE TITLE
Search dropdown: overlap

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#59]
In Chrome I noticed when searching for something that the items overlap with the content below 

<img width="1228" alt="screen shot 2017-12-06 at 11 37 45 am" src="https://user-images.githubusercontent.com/1680051/33674241-e8f0cc82-da7c-11e7-8db2-515ee4177c71.png">

**Comment by kpettinga** [comment]
this should be fixed
