### ISSUE TITLE
Search Box block type

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#60]
Will need the ability to add a search box (not live search) to the main content area of special collections page, and potentially other pages.

**Comment by kpettinga** [comment]
I added a search box block type. @davekellam in light of talking about scoped search boxes, we should provide them options to apply scope to a search box (to only search collections, for instance). I'll let you implement additional options fields for that on the search box block type.

**Comment by davekellam** [comment]
Adding a [supplemental search engine](https://searchwp.com/docs/kb/supplemental-search-step-by-step/) is slightly more involved (required search/results templates), so we can't really add anything to the block until we know the name(s) of any additional SearchWP engines.

**Comment by kpettinga** [comment]
@davekellam I'm a little confused. Would do we need (and from who) to move forward?

**Comment by davekellam** [comment]
We have the search box block in place. I think we either need a SearchWP supplemental search engine if want to search specific results within the site. It might just be that we need a different list of parameters for the "IN" dropdown, which allows for specific results on the WorldCat search. @gabrielo-cuc can you provide us with _exactly_ what you want appearing there?

**Comment by gabriel-ortiz** [comment]
Hi @davekellam, so with regards to scoping to the website's search. Yes I think the vision is to have the website as one of the options in the "IN" location section. I imagine this might change the way you are are doing things, since the search URL is mostly constructed with WorldCat in mind. How difficult would it be to alter the search URL if a user wants to search the website? It would probably ignore what the user inputs for the "AS" parameter and modify the form `action`. 

Let me know if I'm answering what you are asking.

**Comment by davekellam** [comment]
@gabrielo-cuc think I've had all sorts of wires crossed up, I have a tendency to over-complicate things. 

So, we've added in a search box block, which should allow you to put a search box anywhere with or without the local live results. It is possible to do scoped searches for local search results by adding "supplemental search engines" to the SearchWP plugin. Adding one involves some template additions and tweaks. I was thinking that's what Kirk was asking for (me over-complicating). 

The livesearch already includes posts and pages, but it should be possible to direct people to direct people to local search results (sort of how we had it initially). Could get a bit funky with the different form actions. It's easy enough to include a site-specific search box on a page though (i.e. a standard wp search box with or without supplemental search).

So, the question would be, does the search box block work for you for the special collections page, or do you need something more specific there?

**Comment by gabriel-ortiz** [comment]
@davekellam Ah I'm on board now..  So basically, we are talking about whether to make a custom searchbox specific to Special Collections, or reuse the searchbox block that we currently have.... Ideally, I think special collections would like to have a search box dedicated exclusively to them. Maybe we can modify the searchbox to give us the ability to select only one search location. Or maybe a shortcode for a single search location. 

I think a lot of this depends on the time constraints that we are working with now.  How much time would this take? Your time is very valuable, so I think your input on the workload at this point will help us determine which way to go. If we can't create a simple search box right now, then it should be easy for me to make one for the next phase of the website.

**Comment by davekellam** [comment]
I don't think anything is particularly involved (beyond supplemental search templates), really we just need to know what you want. A custom search box is cool. 

* _What sort of box should it be? Does it search WorldCat or something on the site?_ 
* If it's world cat, do you have an example or a setting on the current search box (i.e. the same live search box without the live search and a dropdown preselected)?
* Does the search box _block_ with preselected settings work here?

**Comment by gabriel-ortiz** [comment]
Right on @davekellam. So I have some answers for you. But I'll only be able to speak from my experience as a librarian. In other words, I hope that everyone will be happy, but 99% of what I will suggest is not controversial at all:

- This search box ideally should have the same look-and-feel as the custom block searchbox. Initially, this searchbox will search WorldCat for holdings specifically in the SPCL location. However, there's more. For reasons to hard to explain, SPCL has some of their holdings in WorldCat and the also have holdings in a repository called "Online Archive of california" or OAC  ( http://www.oac.cdlib.org/search?institution=Claremont+Colleges ) 
- Examples of SPCL Worldcat URL: ( https://ccl.on.worldcat.org/search?sortKey=LIBRARY&databaseList=&queryString=kw%3Acitrus&Facet=&database=all&author=&year=all&yearFrom=&yearTo=&language=all&topic=&subscope=wz%3A519%3A%3Azs%3A36307&format=all ) SPCL searches are triggered by the "subscope" portion. If we want to be crude and tasteless, all we need to do is append `&Facet=&database=all&author=&year=all&yearFrom=&yearTo=&language=all&topic=&subscope=wz%3A519%3A%3Azs%3A36307&format=all` to the end of the URL and it will work like a champ.
- Example of OAC URL: ( http://www.oac.cdlib.org/search?query=citrus&institution=Claremont+Colleges ) _note:_ It does not seem possible to scope OAC searches by attribute type, ie (keyword, title, etc). It looks like it can only handle keyword searching.
- Yes, I like your idea of a using the searchbox block with preselected settings for this portion. Riffing off this, it would be cool if we could include a metabox option for preselecting the sources in a `<select>`. Perhaps we add a checkbox list to the searchbox block with options of locations to include in a search. Offhand, we could have a checkbox list that includes Libraries worldwide (default), Claremont Colleges, Special Collections, and OAC. 

I'm here to help with pretty much anything, Lemme know what you need, and we could potentially schedule a phone call if that will be useful. Thanks so much
