### ISSUE TITLE
homepage: quick links

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#62]
Would like ability to add quick links on the homepage per the visual design mockup

<img width="1069" alt="screen shot 2017-12-14 at 4 04 14 pm" src="https://user-images.githubusercontent.com/1680051/34014461-2df35864-e0e9-11e7-8ec3-6e927581a35b.png">

**Comment by kpettinga** [comment]
same as previous issue: #50

**Comment by gabriel-ortiz** [comment]
@kpettinga @Jessdwilson Thanks this looks solid 

- will the URL's work if it's a link to something external to the website?

**Comment by Jessdwilson** [comment]
@gabrielo-cuc  yes, you can also include links to pages external to the website
