### ISSUE TITLE
Events block type

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#63]
Would like ability to add Events carousel to homepage per visual design 

<img width="822" alt="screen shot 2017-12-14 at 4 13 46 pm" src="https://user-images.githubusercontent.com/1680051/34014600-cd6efa42-e0e9-11e7-9414-e6507b46193e.png">

**Comment by kpettinga** [comment]
@davekellam I have the block type and markup in place here. Can you populate the events array with real data?

**Comment by davekellam** [comment]
Should work now. That said, there are currently no events listed. 

@kpettinga There's a date line in the code that can be uncommented, which should pull in old events. You might want to take a look, at the moment we don't seem to be guaranteed a specific image size there.

**Comment by kpettinga** [comment]
Made a few adjustments. Should be all set now.
