### ISSUE TITLE
Hyperlink for promo-scroll item

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#64]
surround images in promo scroll with a call-to-action link

**Comment by kpettinga** [comment]
Added a new field to attachments which can be used to provide a URL. If one is present, it will get added in the promo carousel.

@davekellam I want to make this field editable in the media modal window. I know how to get it to be visible there but I can't figure out how to get it to save when you edit the value (the same way the other fields autosave, with an ajax call I think).    
Any knowledge on that?? My guess is there's some kind of javascript event that a handler needs to be provided for.

![image](https://user-images.githubusercontent.com/1746410/34106212-ab726756-e3f7-11e7-809b-3c94bf1290cb.png)
