### ISSUE TITLE
Footer: school logo band

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#65]
CCL to confirm url links for each logo and provide updated logo for Claremont University Consortium

<img width="884" alt="screen shot 2017-12-14 at 4 20 50 pm" src="https://user-images.githubusercontent.com/1680051/34015466-837d0188-e0ec-11e7-9e54-b6c511699f8a.png">

**Comment by gabriel-ortiz** [comment]
@kpettinga right on! we are loving it.

But now for something political - the logos have to be in a certain order so that some people will be happy. The order is based on founding date, which is correct in the screenshot above. It might be different in the theme?

**Comment by Jessdwilson** [comment]
@davekellam could you help rearrange the logos in the footer so they match the screenshot above?
