### ISSUE TITLE
School selection is not sticking

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#68]
From client:

If you select your school from the dropdown it goes away as soon as you go to a different page. We want that to stick.

**Comment by davekellam** [comment]
This is a cookie issue that we discussed in #35. Basically, we should be able to read the school from a logged in person's cookie and set the colours automatically. But we can't do that until the everything is under the same domain. So, if the demo site is using something like beta.claremont.edu should be able to read the cookie from the claremont.edu authentication server.

The dropdown is there to show that the colour switching works in practice. In theory we could use that dropdown to set our own cookie that we read too. Sort of depends whether the they want the dropdown to actually be there.

**Comment by davekellam** [comment]
<del>So the question is, do we make the dropdown "work" or do we wait until everything is on the same domain?</del>
