### ISSUE TITLE
Flyout menu

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#69]
From client:

On the homepage, the flyout menus (when you click on a IA menu item) go to the right. On all other pages, the flyout is below the main menu instead of to the right – this in effect cuts off the bottom of the flyout menu, as you cannot scroll the menu. We would like all of the flyout menus to go the right, like they do on the homepage.

**Comment by gabriel-ortiz** [comment]
@kpettinga hey this is looking really good - thanks so much

**Comment by Jessdwilson** [comment]
From Dave B.:

> Flyout menus don’t scroll, we are losing some of the info on longer flyout menus – we either need those to scroll or just orient them “landscape” to fly out to the right instead of displaying all the way down (which makes some things unavailable because there is no way to scroll to them).
