### ISSUE TITLE
Archive for databases

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/ccl#72]

**Comment by kpettinga** [comment]
@gabrielo-cuc you can see this working at https://libraryweb.wpengine.com/database-directory/

Note: Right now you don't have any subjects assigned to databases so clicking those links wont show you any databases.

**Comment by gabriel-ortiz** [comment]
Nice work @kpettinga  it's looking  Sharp. So is there a way to assign subjects to databases on import? Or else, would subjects be assigned manually? I'll have to verify that subjects have been assigned in spring share too. Thank you!

**Comment by kpettinga** [comment]
@gabrielo-cuc right now it doesnt appear that any kind of subject is available in the raw data for each database. So they'll need to be assigned manually. If there's a way for you to assign subjects in spring share, then we can probably have subject be auto-assigned to databases on import. But right now there's no data for that kind of thing.

**Comment by gabriel-ortiz** [comment]
@kpettinga Oh i see now -- ok so it looks like we can expand the API route to include subjects  by appending `expand=subjects` to the API request. But then the next step would be to assign the subject to the existing taxonomy.

**Comment by kpettinga** [comment]
hey @gabrielo-cuc thanks for that. I added `expand=subjects` to the API request and put in some logic to assign subject terms to databases. If you re-run the import for databases they should get assigned their respective subjects.

Feel free to close this out unless you have anything else.

**Comment by gabriel-ortiz** [comment]
@kpettinga "Databases by Title" doesn't seem to be working, is it working on your end? I've re-runned the import and published all databases, and when I click on specific letters, there are no databases returned. And there are definitely some within that alphabetical group.  For example there should be a few databases in http://libraryweb.wpengine.com/databases/?begins_with=B Could this be a caching thing? I could try redoing the import.
