### ISSUE TITLE
mobile refinements

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#76]
from the client:
Mobile view – many container problems with text not resizing properly, overlapping, etc.

##

I've attached a few screenshots of issues I noticed, I'll follow up with the client to see if there are additional areas of concern. 

![cclmobile1](https://user-images.githubusercontent.com/1680051/36613622-13548e1e-18a8-11e8-9f3c-19a12c2db6fd.PNG)
![img_6122](https://user-images.githubusercontent.com/1680051/36613632-1a2cd354-18a8-11e8-8cf2-ae1607935f15.PNG)
![img_6124](https://user-images.githubusercontent.com/1680051/36614693-84c43c86-18ab-11e8-9612-8cf982cfa7cd.PNG)

**Comment by Jessdwilson** [comment]
from @gabrielo-cuc 

>  Also something Dave B may or may not have mentioned, but we will need to figure out a way to make the subject librarian's table responsive here: http://libraryweb.wpengine.com/librarians/?sort=subject

**Comment by kpettinga** [comment]
@gabrielo-cuc I think I've made a pass at getting things straightened up on mobile screens. Obviously the site is huge so we may have missed something. If you spot something off, please let us know.

**Comment by gabriel-ortiz** [comment]
Hey @kpettinga Thanks for all the refinements you've made it looks so good! Hey when you get a minute can take a look at the promo scroll overflow in mobile view.  here's a screenshot:
![screenshot_20180316-085733](https://user-images.githubusercontent.com/24301868/37533336-d13b9434-28fe-11e8-86c1-09b7d1f4fbf9.png)

Thanks so much!

**Comment by kpettinga** [comment]
Hey @gabrielo-cuc I think this issue is resolved. Will you confirm? If you're still seeing it, can you let me know what device and browser you're viewing it on?

**Comment by gabriel-ortiz** [comment]
@kpettinga right on! yea we got it fixed. I'm using an android, but i haven't heard anything new from IOS users
