### ISSUE TITLE
 Menu structure for Special Collections homepage

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#77]

**Comment by Jessdwilson** [comment]
From @gabrielo-cuc 

> We have a menu structure already setup for Special Collections. It's located in the secondary header menu. What we need is a way to only show this special collections menu for those pages. I think it's fine if it replaces the regular quick-nav, but if you have additional ideas on design or display - we would love it hear them!

**Comment by kpettinga** [comment]
Hey @gabrielo-cuc I've pushed some code which will allow you to isolate your special collections menu on specific pages. Here's how it works:

- There's now a new Display Location under Menu settings called "Special Collections". You'll want to create a new menu with your special collection items and assign it this location.
- When editing a page, you can now select an option in the sidebar to designate that page as a special collections page. When selected, that page will only display the special collections menu in the quick nav.

Let me know how that works for you.

**Comment by gabriel-ortiz** [comment]
@kpettinga this is pretty awesome! Thank you so much.
