### ISSUE TITLE
News post type 

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/ccl#78]
allowing us to import news items and display them

**Comment by Jessdwilson** [comment]
from @gabrielo-cuc 

> We won't need news imported from anywhere. We can create a custom post type for this. We know we would like a "latest news" feature. Micquel (our director) likes the idea of mixing latest news and upcoming events together in a custom block. This is especially important for the homepage. Alongside, it would be nice to have an **archive page** for this too. I imagine the layout can follow the same UI as many of our other archive pages.

**Comment by kpettinga** [comment]
@gabrielo-cuc I've built out a few things here.

- A "News" post type
- News Archive template ( template: archive-news.php )( url: `[site url]/news/` )
- New and Events content block type.
    - **Note**: Events must be imported into wordpress before they will be available to display.

**Comment by gabriel-ortiz** [comment]
@kpettinga @Jessdwilson This is perfect. Thanks so much
