### ISSUE TITLE
Archive for Staff

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/ccl#79]

**Comment by kpettinga** [comment]
@gabrielo-cuc There is now a page template call Staff Archive which can be used to create a page for all non-librarian staff.

**Comment by gabriel-ortiz** [comment]
Right on @kpettinga  looks solid so far! Thank you so much for doing this. There are a couple refinements I'd like to make... do you mind if I take it from here?

- [x] I'm seeing students mixed in there. So I think I'll add a staff taxonomy, and we can target the staff taxonomy

- [x] I'd like to get the title of each staff member - I'll work on setting that up

- [x] I'd also like to include at least email for everyone. Prolly need to create a meta box field for that

**Comment by kpettinga** [comment]
@gabrielo-cuc, yes, please feel free to take over
