### ISSUE TITLE
Flyout menu getting chopped off by window

### ISSUE THREAD

**Issue by gabriel-ortiz** [ObjectiveSubject/ccl#84]
Hey @kpettinga  @Jessdwilson @davekellam ,

We are noticing that parts of our flyout menu in quick-nav are still being chopped by the browser window. This is mostly true for our "Research Support" section. Can we make the flyout here a scroll, or maybe we can make the flyout container to be 2/3rds or something like that?

**Comment by kpettinga** [comment]
@gabrielo-cuc this should be fixed now. Please close if there's nothing further.

**Comment by gabriel-ortiz** [comment]
@kpettinga Amazing and elegant fix.... Thanks!
