### ISSUE TITLE
Rooms: add spaces and front-end functionality

### ISSUE THREAD

**Issue by davekellam** [ObjectiveSubject/ccl#9]

**Comment by davekellam** [comment]
Most of the backend functions are in place for importing rooms. We now need to add the post and work on the front-end reservation flow.

**Comment by kpettinga** [comment]
@davekellam i've got a static front-end setup here. Once we get some rooms imported you can take a look and start wiring it up.

**Comment by davekellam** [comment]
It's alive! There's still a thing with the end-time to sort out (it's hardcoded at the moment), but initial wiring together is a success. 

![screen shot 2017-10-24 at 3 28 04 pm](https://user-images.githubusercontent.com/60804/31963847-156ca6f6-b8d0-11e7-8786-6ffd90893215.png)

Then there's still a need for some functions related to bookings and available hours. Not sure if those should be a new issue, or carry on here.

**Comment by kpettinga** [comment]
Setup the room reservation template on the staging site but it seems the ajax requests are all failing. Schedules for each day aren't populating. @davekellam any ideas?

http://libraryweb.wpengine.com/meeting-and-presentation-spaces/

**Comment by davekellam** [comment]
Seems the `check_ajax_referer` nonces are problematic on the production server. I'm assuming it's something to do with caching. I'm not 💯 that they're needed in this instance (or just in admin), but will investigate further.

**Comment by davekellam** [comment]
So, the nonce check is only failing for logged in users. That's a small subset. Ok for now, but would be helpful to track down why it's happening.

**Comment by kpettinga** [comment]
Since we have a basic working system in place here, and other issues are beginning to pop up, I'm spinning this out into separate issues.

See #45, and #46

**Comment by kpettinga** [comment]
See http://libraryweb.wpengine.com/meeting-and-presentation-spaces/ to try out the room reservation system.
